version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./fit_tracker:/fit_tracker
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fit_tracker:fit_tracker@db:5432/fit_tracker_dev
    depends_on:
      - db
  db:
    image: postgres:15.2-bullseye
    restart: always
    command: "-c fsync=off"  # baza działa szybciej, tylko dev
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "14432:5432"
    environment:
      - POSTGRES_USER=fit_tracker
      - POSTGRES_PASSWORD=fit_tracker
      - POSTGRES_DB=fit_tracker_dev
volumes:
  db-data: