# Generated by Django 4.2.1 on 2023-05-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(blank=True, choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('intensity', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=10)),
                ('length_time', models.DurationField()),
                ('start_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
