# Generated by Django 4.2.1 on 2023-05-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10)),
                ('total_distance', models.DecimalField(decimal_places=1, max_digits=10)),
                ('total_number_sessions', models.IntegerField()),
                ('total_length_time', models.DurationField()),
                ('last_session', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.summary'),
        ),
    ]
