# Generated by Django 4.2.1 on 2023-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_summary_last_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='summary',
        ),
        migrations.AddField(
            model_name='session',
            name='average_length_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='last_session',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='total_distance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
