# Generated by Django 4.2.1 on 2023-05-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_session_start_date_remove_session_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='average_length_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='last_session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='total_distance',
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10)),
                ('total_distance', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('total_number_sessions', models.IntegerField(null=True)),
                ('average_length_time', models.DurationField(null=True)),
                ('last_session', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.summary'),
        ),
    ]
