# Generated by Django 4.2.1 on 2023-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_session_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('running', 'running'), ('cycling', 'cycling'), ('hiking', 'hiking'), ('swimming', 'swimming'), ('walking', 'walking')], max_length=10),
        ),
    ]
