# Generated by Django 4.2.1 on 2023-05-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='average_length_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_session',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_distance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_number_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
