# Generated by Django 4.2.1 on 2023-06-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_session_options_alter_summary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.summary'),
        ),
    ]
