# Generated by Django 4.2.2 on 2023-06-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_session_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.summary'),
        ),
    ]
