# Generated by Django 4.2.2 on 2023-06-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_session_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['user', '-summary_type']},
        ),
    ]
